apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq
  name: drkiq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drkiq
    spec:
      containers:
      - env:
        - name: CACHE_URL
          value: redis://redis:6379/0
        - name: DATABASE_URL
          value: postgresql://drkiq:yourpassword@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000
        - name: JOB_WORKER_URL
          value: redis://redis:6379/0
        - name: LISTEN_ON
          value: 0.0.0.0:8000
        - name: SECRET_TOKEN
          value: asecuretokenwouldnormallygohere
        - name: WORKER_PROCESSES
          value: "1"
        image: drkiq:tag
        name: drkiq
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /drkiq
          name: drkiq-claim0
      restartPolicy: Always
      volumes:
      - name: drkiq-claim0
        persistentVolumeClaim:
          claimName: drkiq-claim0
status: {}
